
version: '3'
services:

  server:
    image: node:20.15
    container_name: server
    ports:
      - $NODE_PORT:$NODE_PORT
    volumes:
      - ./server:/app
    environment:
      - MONGO_URI=mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@mongo:27017/${MONGODB_DATABASE}?authSource=admin
    depends_on:
      - mongo
    tty: true

  client:
    image: node:20.15
    container_name: client
    ports:
      - $REACT_PORT:$REACT_PORT
    volumes:
      - ./client:/app
    tty: true

  mongo:
    image: mongo:noble
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    restart: always

  mongo-express:
    image: mongo-express:1.0.2-18
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USER}  
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}  
    depends_on:
      - mongo
    restart: always
 
  minio:
    image: minio/minio:RELEASE.2024-02-14T21-36-02Z
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ~/minio/data:/data
    command: server /data --console-address ":9001"

volumes:
  mongo-data:
    driver: local